language: python
python:
  - "3.4"
before_install:
  - mv travis/secrets.yaml secrets.yaml
  - mv travis/cameras.yaml inlcudes/cameras.yaml
  - mv travis/zones.yaml includes/zones.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
