language: python
python:
  - "3.4"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis_cameras.yaml includes/cameras.yaml
  - mv travis/travis_zones.yaml includes/zones.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
