- id: '1'
  alias: "Licht in der D\xE4mmerung"
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  condition:
    condition: state
    entity_id: group.bewohner
    state: home
  action:
    service: light.turn_on
    entity_id: group.Wohnzimmer

- id: '2'
  alias: Billy auf dem Heimweg
  trigger:
    platform: state
    entity_id: device_tracker.jiphone_ios
    from: Unterschleissheim
    to: not_home
    for:
      minutes: 10
  condition:
    condition: time
    after: '15:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: notify.elisabeth
    data_template:
      title: Billy auf dem Heimweg
      message: 'Billy ist nun auf dem Heimweg. ETA: {{ states.sensor.julian_home_travel.attributes.duration_in_traffic
        }}

        '

- id: '3'
  alias: Billy zu Hause
  trigger:
    platform: state
    entity_id: device_tracker.jiphone, device_tracker.windowsphone
    from: not_home
    to: home
  action:
  - service: notify.julian
    data:
      title: Billy
      message: ist jetzt zu Hause
  - service: switch.turn_off
    entity_id: switch.callforwarding_2

- id: '4'
  alias: Billy unterwegs
  trigger:
    platform: state
    entity_id: device_tracker.jiphone, device_tracker.windowsphone
    from: home
    to: not_home
  action:
  - service: notify.julian
    data:
      title: Billy
      message: ist unterwegs
  - service: switch.turn_on
    entity_id: switch.callforwarding_2

- id: '5'
  alias: Rufumleitung Billy aktiviert
  trigger:
  - entity_id: switch.callforwarding_2
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Rufumleitung aktiviert
      title: Billy
    service: notify.julian

- id: '6'
  alias: Rufumleitung Billy deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_2
    from: 'on'
    to: 'off'
  action:
  - service: notify.julian
    data:
      title: Billy
      message: Rufumleitung deaktiviert

- id: '7'
  alias: Rufumleitung Hausverwaltung aktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'off'
    to: 'on'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Hausverwaltung aktiviert

- id: '8'
  alias: Rufumleitung Hausverwaltung deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'on'
    to: 'off'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Hausverwaltung deaktiviert

- id: '20'
  alias: Rufumleitung Kanzlei aktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'off'
    to: 'on'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Kanzlei aktiviert

- id: '21'
  alias: Rufumleitung Kanzlei deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'on'
    to: 'off'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Kanzlei deaktiviert

- id: '9'
  alias: Lilly zu Hause
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: not_home
    to: home
  action:
  - service: notify.julian
    data:
      title: Lilly
      message: ist jetzt zu Hause
  - service: switch.turn_off
    entity_id:
    - switch.callforwarding_0
    - switch.callforwarding_1

- id: '10'
  alias: Lilly unterwegs
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: home
    to: not_home
  action:
  - service: notify.julian
    data:
      title: Lilly
      message: ist jetzt unterwegs
  - service: switch.turn_on
    entity_id:
    - switch.callforwarding_0
    - switch.callforwarding_1

- id: '11'
  alias: Jemand zu Hause
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  action:
  - service: climate.set_away_mode
    data:
      away_mode: false
  - service: notify.julian
    data:
      title: Niemand
      message: ist mehr zu Hause

- id: '12'
  alias: Niemand zu Hause
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
    for:
      minutes: 10
  action:
    service: notify.julian
    data:
      title: Niemand
      message: ist mehr zu Hause

- id: '13'
  alias: Sonos Durchsage
  trigger:
    platform: state
    entity_id: input_boolean.mytest
  action:
    service: script.sonos_say
    data:
      sonos_entity: media_player.schlafzimmer
      volume: 0.5
      message: Billy testet nur die Sprachwiedergabe!
      delay: 00:00:05

- id: '14'
  alias: Ab ins Bett
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: group.bewohner
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.Goodnite

- id: '15'
  alias: Gute Nacht
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: light.turn_off
    data:
      transition: 1

- id: '16'
  alias: Camera Motion
  trigger:
  - platform: state
    entity_id: sensor.camera
    to: motion
  action:
    service: notify.julian
    data:
      title: Camera
      message: Motion captured at neighbourhoodwatch
      data:
        url: http://neighbourhoodwatch:8081
        tag: neighbourhoodwatch_motion

- id: '17'
  alias: Home Assistant Update
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.julian
    data:
      message: "Version {{ states.updater.updater.state }} von Home Assistant ist\
        \ nun verf\xFCgbar."

- id: '18'
  alias: "Wohnungst\xFCr noch offen"
  trigger:
  - platform: state
    entity_id: binary_sensor.leq0758071_state
    to: 'on'
    for:
      minutes: 2
  action:
  - service: notify.all
    data:
      message: "Wohnungst\xFCr noch offen."

- id: '19'
  alias: Curcuma braucht Wasser
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_1_moisture
    below: 15
  action:
  - service: notify.julian
    data:
      message: Die Curcuma braucht Wasser.

- id: "22"
  alias: "Detected a face"
  trigger:
  - platform: event
    event_type: image_processing.detect_face
    event_data:
      entity_id: image_processing.Gesichtserkennung
  action:
    - service: notify.julian
      data:
        message: "Detected a face."
        target:
          - notify_all

- id: '23'
  alias: "Wetterwarnung München"
  initial_state: True
  trigger:
    platform: numeric_state
    entity_id: sensor.warnings_muenchen_current_warning_level
    above: 2
  action:
    - service: notify.julian
      data:
        message:  |
          {{ states.sensor.warnings_muenchen_current_warning_level.attributes.region_name }}
          {% if states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_headline is defined %}
          {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_headline }}
          Warnstufe: {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_level }}
          Von: {{ as_timestamp(states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_start) | timestamp_custom("%a %d.%m.%Y %H:%M",true) }}
          Bis: {{ as_timestamp(states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_end) | timestamp_custom("%a %d.%m.%Y %H:%M",true) }}
          {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_description }}
          {% endif %}

- id: '1506654915171'
  alias: Fernsehlicht an
  trigger:
  - platform: state
    entity_id: device_tracker.tv
    from: not_home
    to: home
  action:
  - data:
      entity_id: scene.Fernsehen
    service: scene.turn_on

- id: '1506655401045'
  alias: Fernsehlicht aus
  trigger:
  - platform: state
    entity_id: device_tracker.tv
    from: home
    to: not_home
  action:
  - delay: '3:00'
  - data:
      entity_id:
      - light.eckstrahler
      - light.lightstrip
    service: light.turn_off
