- id: '1'
  alias: Licht in der Dämmerung
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  condition:
    condition: state
    entity_id: group.bewohner
    state: home
  action:
    service: light.turn_on
    entity_id: group.Wohnzimmer
- id: '2'
  alias: Billy auf dem Heimweg
  trigger:
    platform: state
    entity_id: device_tracker.jiphone_ios
    from: Unterschleissheim
    to: not_home
    for:
      minutes: 10
  condition:
    condition: time
    after: '15:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: notify.elisabeth
    data_template:
      title: Billy auf dem Heimweg
      message: 'Billy ist nun auf dem Heimweg. ETA: {{ states.sensor.julian_home_travel.attributes.duration_in_traffic
        }}

        '
- id: '3'
  alias: Billy zu Hause
  trigger:
  - entity_id: device_tracker.jiphone_ios
    from: not_home
    platform: state
    to: home
  action:
  - data:
      message: ist jetzt zu Hause
      title: Billy
    service: notify.julian
  - entity_id: switch.callforwarding_2
    service: switch.turn_off
- id: '4'
  alias: Billy unterwegs
  trigger:
    platform: state
    entity_id: device_tracker.jiphone, device_tracker.windowsphone
    from: home
    to: not_home
  action:
  - service: notify.julian
    data:
      title: Billy
      message: ist unterwegs
  - service: switch.turn_on
    entity_id: switch.callforwarding_2
- id: '5'
  alias: Rufumleitung Billy aktiviert
  trigger:
  - entity_id: switch.callforwarding_2
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Rufumleitung aktiviert
      title: Billy
    service: notify.julian
- id: '6'
  alias: Rufumleitung Billy deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_2
    from: 'on'
    to: 'off'
  action:
  - service: notify.julian
    data:
      title: Billy
      message: Rufumleitung deaktiviert
- id: '7'
  alias: Rufumleitung Hausverwaltung aktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'off'
    to: 'on'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Hausverwaltung aktiviert
- id: '8'
  alias: Rufumleitung Hausverwaltung deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'on'
    to: 'off'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Hausverwaltung deaktiviert
- id: '20'
  alias: Rufumleitung Kanzlei aktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'off'
    to: 'on'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Kanzlei aktiviert
- id: '21'
  alias: Rufumleitung Kanzlei deaktiviert
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'on'
    to: 'off'
  action:
  - service: notify.elisabeth
    data:
      title: Lilly
      message: Rufumleitung Kanzlei deaktiviert
- id: '9'
  alias: Lilly zu Hause
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: not_home
    to: home
  action:
  - service: notify.julian
    data:
      title: Lilly
      message: ist jetzt zu Hause
  - service: switch.turn_off
    entity_id:
    - switch.callforwarding_0
    - switch.callforwarding_1
- id: '10'
  alias: Lilly unterwegs
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: home
    to: not_home
  action:
  - service: notify.julian
    data:
      title: Lilly
      message: ist jetzt unterwegs
  - service: switch.turn_on
    entity_id:
    - switch.callforwarding_0
    - switch.callforwarding_1
- id: '11'
  alias: Jemand zu Hause
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  action:
  - service: climate.set_away_mode
    data:
      away_mode: false
  - service: notify.julian
    data:
      title: Niemand
      message: ist mehr zu Hause
- id: '12'
  alias: Niemand zu Hause
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
    for:
      minutes: 10
  action:
    service: notify.julian
    data:
      title: Niemand
      message: ist mehr zu Hause
- id: '13'
  alias: Sonos Durchsage
  trigger:
    platform: state
    entity_id: input_boolean.mytest
  action:
    service: script.sonos_say
    data:
      sonos_entity: media_player.schlafzimmer
      volume: 0.5
      message: Billy testet nur die Sprachwiedergabe!
      delay: 00:00:05
- id: '14'
  alias: Ab ins Bett
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: group.bewohner
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.good_night
- id: '15'
  alias: Gute Nacht
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: light.turn_off
    data:
      transition: 1
- id: '16'
  alias: Camera Motion
  trigger:
  - platform: state
    entity_id: sensor.camera
    to: motion
  action:
    service: notify.julian
    data:
      title: Camera
      message: Motion captured at neighbourhoodwatch
      data:
        url: http://neighbourhoodwatch:8081
        tag: neighbourhoodwatch_motion
- id: '17'
  alias: Home Assistant Update
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.julian
    data:
      message: Version {{ states.updater.updater.state }} von Home Assistant ist nun
        verfügbar.
- id: '19'
  alias: Curcuma braucht Wasser
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_1_moisture
    below: 15
  action:
  - service: notify.julian
    data:
      message: Die Curcuma braucht Wasser.

- id: '22'
  alias: Detected a face
  trigger:
  - event_data:
      entity_id: face_detection_wohnzimmer
    event_type: image_processing.detect_face
    platform: event
  action:
  - data:
      message: Detected a face.
    service: notify.julian

- id: '23'
  alias: Wetterwarnung München
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.warnings_muenchen_current_warning_level
    above: 2
  action:
  - service: notify.julian
    data:
      message: '{{ states.sensor.warnings_muenchen_current_warning_level.attributes.region_name
        }}

        {% if states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_headline
        is defined %}

        {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_headline
        }}

        Warnstufe: {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_level
        }}

        Von: {{ as_timestamp(states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_start)
        | timestamp_custom("%a %d.%m.%Y %H:%M",true) }}

        Bis: {{ as_timestamp(states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_end)
        | timestamp_custom("%a %d.%m.%Y %H:%M",true) }}

        {{ states.sensor.warnings_muenchen_current_warning_level.attributes.warning_1_description
        }}

        {% endif %}

        '
- id: '1506654915171'
  alias: Fernsehlicht an
  trigger:
  - entity_id: device_tracker.tv
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data:
      entity_id: scene.Fernsehen
    service: scene.turn_on
- id: '1506655401045'
  alias: Fernsehlicht aus
  trigger:
  - entity_id: device_tracker.tv
    from: home
    platform: state
    to: not_home
  action:
  - delay: 00:03:00
  - data:
      entity_id:
      - light.eckstrahler
      - light.lightstrip
    service: light.turn_off
- action:
  - data:
      message: detektiert
      title: Bewegung in der Schokoladenfabrik
    service: notify.julian
  alias: Bewegungsmelder Schokoladenfabrik
  condition: []
  id: '9522507257599'
  trigger:
  - payload: 'on'
    platform: mqtt
    topic: augustenstrasse/dafang1/motion
- action:
  - data:
      message: detektiert
      title: Bewegung im Drachenhorst
    service: notify.julian
  alias: Bewegungsmelder Drachenhorst
  condition: []
  id: '1522507257594'
  trigger:
  - payload: 'on'
    platform: mqtt
    topic: drachenhorst/dafang2/motion
- action:
  - data:
      message: detektiert
      title: Bewegung in der Augustenstrasse
    service: notify.julian
  alias: Bewegungsmelder Augustenstrasse
  condition: []
  id: '9522507257594'
  trigger:
  - payload: 'ON'
    platform: mqtt
    topic: augustenstrasse/dafang3/motion
- action:
  - delay: 00:00:02
  - service: python_script.update_zone_occupancies
  alias: Update Occupants
  condition: []
  id: '1522510838998'
  initial_state: 'on'
  trigger:
  - entity_id: device_tracker.jiphone_ios
    platform: state
  - entity_id: device_tracker.eiphone_ios
    platform: state
- action:
  - data:
      entity_id: switch.dafang1_motion_detection
    service: switch.turn_on
  - data:
      message: verlassen
      title: Schokoladenfabrik
    service: notify.julian
  alias: Schokoladenfabrik verlassen
  condition: []
  id: '1522573800854'
  trigger:
  - below: '1'
    entity_id: sensor.occupants_geretsried
    platform: numeric_state
- action:
  - data:
      entity_id: switch.dafang1_motion_detection
    service: switch.turn_off
  - data:
      message: bewohnt
      title: Schokoladenfabrik
    service: notify.julian
  alias: Schokoladenfabrik bewohnt
  condition: []
  id: '6612526605275'
  trigger:
  - above: '0'
    entity_id: sensor.occupants_geretsried
    platform: numeric_state
- action:
  - data:
      entity_id: switch.dafang2_motion_detection
    service: switch.turn_on
  - data:
      message: verlassen
      title: Drachenhorst
    service: notify.julian
  alias: Drachenhorst verlassen
  condition: []
  id: '1522526500754'
  trigger:
  - below: '1'
    entity_id: sensor.occupants_irma_wenke_str
    platform: numeric_state
- action:
  - data:
      entity_id: switch.dafang2_motion_detection
    service: switch.turn_off
  - data:
      message: bewohnt
      title: Drachenhorst
    service: notify.julian
  alias: Drachenhorst bewohnt
  condition: []
  id: '1522526605275'
  trigger:
  - above: '0'
    entity_id: sensor.occupants_irma_wenke_str
    platform: numeric_state
- action:
  - data:
      entity_id: switch.dafang3_motion_detection
    service: switch.turn_on
  - data:
      message: verlassen
      title: Augustenstrasse
    service: notify.julian
  alias: Augustenstrasse verlassen
  condition: []
  id: '1522573800754'
  trigger:
  - below: '1'
    entity_id: sensor.occupants_home
    platform: numeric_state
- action:
  - data:
      entity_id: switch.dafang3_motion_detection
    service: switch.turn_off
  - data:
      message: bewohnt
      title: Augustenstrasse
    service: notify.julian
  alias: Augustenstrasse bewohnt
  condition: []
  id: '6622526605275'
  trigger:
  - above: '0'
    entity_id: sensor.occupants_home
    platform: numeric_state
- action:
  - data:
      message: That's an example that
      title: Send a message
    service: notify.julian
  alias: Neuer snap Augustenstr
  condition: []
  id: '1523685773653'
  trigger:
  - platform: mqtt
    topic: augustenstrasse/dafang3/motion/snapshot

- id: '1532501801403'
  alias: Detect Billys Face
  trigger:
  - event_data:
      entity_id: image_processing.face_id_wohnzimmer
    event_type: image_processing.detect_face
    platform: event
  condition: []
  action:
  - service: notify.julian
    data_template:
      title: Face recognized
      message: 'Recognized {{ trigger.event.data.name }} with probability {{ trigger.event.data.confidence }}'
- id: '1536030351586'
  alias: Kaffeemaschine an
  trigger:
  - at: '7:30'
    platform: time
  action:
  - data:
      entity_id: light.onoff_plug_2
    service: light.turn_on
- id: '1536030408272'
  alias: Kaffeemaschine aus
  trigger:
  - at: '8:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.onoff_plug_2
    service: light.turn_off
