homeassistant:
  # Name of the location where Home Assistant is running
  name: Augustenstrasse
  # Location required to calculate the time the sun rises and sets
  latitude: 48.151507
  longitude: 11.564757
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 540
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

# Enables the frontend
frontend:

map:

config:

http:
  api_password: !secret homeassistant_api_password
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path
  base_url: !secret homeassistant_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Keep data 10 days
recorder:
    purge_keep_days: 10

# Track the sun
sun:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# ios
ios:

homekit:
  filter:
    include_domains:
      - light

# expose python_scripts as services
python_script:

# telegram
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id_julian
      - !secret telegram_id_elisabeth

# Text to speech
tts:
  platform: google
  language: 'de'

# homematic
homematic:
  interfaces:
    wireless:
      host: 192.168.181.24
      resolvenames: metadata

# fritz
#fritz:
#  fritzboxes:
#   - host: 192.168.181.1
#     password: !secret fritzbox_password

# lgtv & onkyo receiver
media_player:
  - platform: lg_netcast
    host: 192.168.181.34
    access_token: SMQRSA
  - platform: onkyo
    host: 192.168.179.39
    name: Receiver

# hues
hue:
  bridges:
    - host: 192.168.181.20
      allow_unreachable: true

# locative & fritz
device_tracker:
  - platform: locative
  - platform: fritz

#bmw_connected_drive:
#  Xsy:
#    username: !secret bmw_connected_drive_user
#    password: !secret bmw_connected_drive_password
#    region: rest_of_world

# mqtt with autodiscovery
mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

# Includes

binary_sensor: !include includes/binary_sensors.yaml
sensor: !include includes/sensors.yaml
camera: !include includes/cameras.yaml
image_processing: !include includes/image_processing.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
script: !include scripts.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml
notify: !include includes/notify.yaml
logger: !include includes/logger.yaml
automation: !include automations.yaml
# automation: !include includes/experimental_automations.yaml
alert: !include includes/alerts.yaml
plant: !include includes/plants.yaml
