- alias: "Licht in der D채mmerung"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: light.turn_on
    entity_id: group.Wohnzimmer
      
- alias: "Billy auf dem Heimweg"
  trigger:
    platform: state
    entity_id: device_tracker.14ab5149cee943dcb7726ed31b28cffc
    from: 'parkring'
    to: 'not_home'
    for: 
      minutes: 10
  condition:
      condition: time
      after: '15:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: notify.Augustenbot
    data_template:
      message: >
        Billy ist nun auf dem Heimweg.
        ETA: {{ states.sensor.julian_home_travel.attributes.duration_in_traffic }}
      target: notify_julian
      
- alias: 'Billy zu Hause' 
  trigger:
    platform: state
    entity_id: device_tracker.jiphone, device_tracker.windowsphone
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.Augustenbot
      data:
        title: "Billy"
        message: "ist jetzt zu Hause"
        target: notify_julian
    - service: switch.turn_off
      entity_id: switch.callforwarding_0

- alias: 'Billy unterwegs' 
  trigger:
    platform: state
    entity_id: device_tracker.jiphone, device_tracker.windowsphone
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.Augustenbot
      data:
        title: "Billy"
        message: "ist unterwegs"
        target: notify_julian
    - service: switch.turn_on
      entity_id: switch.callforwarding_0
      
- alias: 'Rufumleitung Billy aktiviert' 
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'off'
    to: 'on'
  action:
    - service: notify.Augustenbot
      data:
        title: "Billy"
        message: "Rufumleitung aktiviert"
        target: notify_julian
        
- alias: 'Rufumleitung Billy deaktiviert' 
  trigger:
    platform: state
    entity_id: switch.callforwarding_0
    from: 'on'
    to: 'off'
  action:
    - service: notify.Augustenbot
      data:
        title: "Billy"
        message: "Rufumleitung deaktiviert"
        target: notify_julian
        
- alias: 'Rufumleitung Lilly aktiviert' 
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'off'
    to: 'on'
  action:
    - service: notify.Augustenbot
      data:
        title: "Lilly"
        message: "Rufumleitung aktiviert"
        target: notify_julian
        
- alias: 'Rufumleitung Lilly deaktiviert' 
  trigger:
    platform: state
    entity_id: switch.callforwarding_1
    from: 'on'
    to: 'off'
  action:
    - service: notify.Augustenbot
      data:
        title: "Lilly"
        message: "Rufumleitung deaktiviert"
        target: notify_julian
      
- alias: 'Lilly zu Hause' 
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.Augustenbot
      data:
        title: "Lilly"
        message: "ist jetzt zu Hause"
        target: notify_julian
    - service: switch.turn_off
      entity_id: switch.callforwarding_1
      
- alias: 'Lilly unterwegs' 
  trigger:
    platform: state
    entity_id: device_tracker.eiphone
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.Augustenbot
      data:
        title: "Lilly"
        message: "ist jetzt unterwegs"
        target: notify_julian
    - service: switch.turn_on
      entity_id: switch.callforwarding_1
      
- alias: "Jemand zu Hause"
  trigger:
    - platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'
  action:
    service: climate.set_away_mode
    data:
      away_mode: off

- alias: "Niemand zu Hause"
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 10
  action:
    service: notify.Augustenbot
    data:
      title: "Niemand"
      message: "ist mehr zu Hause"
      target: notify_julian
      
- alias: 'Sonos Durchsage'
  trigger:
    platform: state
    entity_id: input_boolean.mytest
  action:   
    service: script.sonos_say
    data:
      sonos_entity: media_player.schlafzimmer
      volume: 0.5
      message: 'Billy testet nur die Sprachwiedergabe!'
      delay: '00:00:05'
      
- alias: 'Ab ins Bett'
  trigger:
    platform: time
    after: "22:00:00"
  condition:
    condition: state
    entity_id: group.family
    state: 'home'    
  action:   
    service: scene.turn_on
    entity_id: scene.Goodnite
    
- alias: 'Gute Nacht'
  trigger:
    platform: time
    after: '22:30:00'
  action:
    service: light.turn_off
    entity_id:
      - group.all_devices
    data:
      transition: 900

- alias: "Camera Motion"
  trigger:
    - platform: state
      entity_id: sensor.camera
      to: 'motion'
  action:
    service: notify.Augustenbot
    data:
      title: "Camera "
      message: "Motion captured at neighbourhoodwatch"
      data:
        url: "http://neighbourhoodwatch:8081"
        tag: 'neighbourhoodwatch_motion'
      target:
        - notify_julian

- alias: "Home Assistant Update"
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
      service: notify.Augustenbot
      data:
        message: "Version {{ states.updater.updater.state }} von Home Assistant ist nun verf체gbar."
        target:
        - notify_all
        
- alias: "Wohnungst체r noch offen"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      to: 'on'
      for:
        minutes: 2
  action:
    - service: notify.Augustenbot
      data:
        message: "Wohnungst체r noch offen."
        target:
          - notify_all
   
- alias: "Curcuma braucht Wasser"
  trigger:
    - platform: numeric_state
      entity_id: sensor.sensor_1_moisture
      below: 15
  action:
    - service: notify.Augustenbot
      data:
        message: "Die Curcuma braucht Wasser."
        target:
          - notify_all
