- platform: dlib_face_detect
  name: Gesichtserkennung
  source:
  - entity_id: camera.Drachenhorst
  - entity_id: camera.villa_emerald_vorne


- platform: dlib_face_identify
  name: Gesichtsidentifizierung
  source:
  - entity_id: camera.Drachenhorst
  - entity_id: camera.villa_emerald_vorne
  faces:
    julian: ~/.homeassistant/faces/julian.jpg
    elisabeth: ~/.homeassistant/faces/elisabeth.jpg
    birgit: ~/.homeassistant/faces/birgit.jpg
    klaus: ~/.homeassistant/faces/klaus.jpg
    laura: ~/.homeassistant/faces/laura.jpg
