
- platform: telegram
  name: AugustenBot
  api_key: !secret telegram_api
  chat_id: !secret telegram_chat_id

- platform: telegram
  name: telegram_julian
  chat_id: !secret telegram_id_julian

- platform: telegram
  name: telegram_elisabeth
  chat_id: !secret telegram_id_elisabeth

- platform: group
  name: julian
  services:
    - service: telegram_julian
    # add further ways to notify the user

- platform: group
  name: elisabeth
  services:
    - service: telegram_elisabeth
    # add further ways to notify the user

- platform: group
  name: all
  services:
    - service: telegram_julian
    - service: telegram_elisabeth
